ProjetoIntegrador/Controllers/AmigosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PagedList;
using ProjetoIntegrador.Models;
using System.Data.Entity;
using ProjetoIntegrador.Bussiness;

namespace ProjetoIntegrador.Controllers
{
    [Authorize]
    public class AmigosController : Controller
    {
        // Context for base test
        projetointegradorContext dbcontext = new projetointegradorContext();

        //
        // GET: /Amigos/Index
        public ActionResult Index(int? page)
        {
            int pageSize = 15;
            int pageNumber = (page ?? 1);

            var myamigos = dbcontext.amigoes.Where(x => x.IDUSUARIO1 == UserBussiness.IdUser && x.ATIVO == true).ToList();

            return View(myamigos.ToPagedList(pageNumber, pageSize));
        }

        //
        // POST: /Amigos/ListAmigos
        public ActionResult ListAmigos(string search, int? page)
        {
            int pageSize = 15;
            int pageNumber = (page ?? 1);

            var listusers = dbcontext.usuarios.Where(x => x.IDUSUARIO != UserBussiness.IdUser && x.ATIVO == true).ToList();

            if (!string.IsNullOrEmpty(search))
            {
                listusers = listusers.Where(x => x.NOMEUSUARIO.ToLower().Contains(search.ToLower())).ToList();
            }

            return View(listusers.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Amigos/AmigoInfo
        public ActionResult AmigoInfo(int? id)
        {
            var amigo = dbcontext.usuarios.Find(id);

            List<arquivo> filesList = dbcontext.arquivoes.Where(x => x.IDUSUARIO == id).ToList();
            ViewBag.Files = filesList;

            return View(amigo);
        }

        //
        // GET: /Amigos/AmigoInfo
        public ActionResult SearchAmigos(int? id)
        {
            return View();
        }


        //
        // GET: /Amigos/AmigoInfo
        public ActionResult AdcionarAmizade(int id)
        {
            var amigo = dbcontext.amigoes.Where(x => x.IDUSUARIO1 == UserBussiness.IdUser && x.IDUSUARIO2 == id).FirstOrDefault();
            if (amigo != null)
            {
                amigo.ATIVO = true;
                dbcontext.SaveChanges();
            }
            else
            {
                try
                {
                    amigo amizade = new amigo();
                    amizade.IDUSUARIO1 = UserBussiness.IdUser;
                    amizade.IDUSUARIO2 = id;
                    amizade.ATIVO = true;
                    dbcontext.amigoes.Add(amizade);
                    dbcontext.SaveChanges();
                }
                catch (Exception error)
                {
                    throw new Exception();
                }
            }

            return RedirectToAction("AmigoInfo", new { id = id });
        }


        //
        // GET: /Amigos/ExcluirAmizade
        public ActionResult ExcluirAmizade(int id)
        {
            try
            {
                var amigo = dbcontext.amigoes.Where(x => x.IDUSUARIO1 == UserBussiness.IdUser && x.IDUSUARIO2 == id).FirstOrDefault();
                if (amigo != null)
                {
                    amigo.ATIVO = false;
                    dbcontext.SaveChanges();
                }
            }
            catch (Exception error)
            {
                throw new Exception();
            }

            return RedirectToAction("AmigoInfo", new { id = id });
        }
    }
}

ProjetoIntegrador/Controllers/ArquivosController.cs
using ProjetoIntegrador.Bussiness;
using ProjetoIntegrador.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PagedList;
using System.Configuration;

namespace ProjetoIntegrador.Controllers
{
    [Authorize]
    public class ArquivosController : Controller
    {
        projetointegradorContext dbcontext = new projetointegradorContext();

        //
        // GET: /Arquivos/Index
        public ActionResult Index(int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            var files = dbcontext.arquivoes.Where(x => x.IDUSUARIO == UserBussiness.IdUser && x.ATIVO == true).ToList();

            return View(files.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Arquivos/ArquivoInfo
        public ActionResult ArquivoInfo(int? id)
        {
            var file = dbcontext.arquivoes.Where(x => x.IDARQUIVO == id && x.ATIVO == true).FirstOrDefault();
            return View(file);
        }

        //
        // GET: /Arquivos/DeleteFile
        public ActionResult DeleteFile(int? id)
        {
            // Não vamos excluir o arquivo apenas inativalo
            var file = dbcontext.arquivoes.Find(id);
            file.ATIVO = false;
            dbcontext.SaveChanges();

            return RedirectToAction("Index", new { msg = "filerm" });
        }


        //
        // EDIT: /Arquivos/Edit
        [HttpPost]
        public void Edit(int id, string descricao)
        {
            try
            {
                var files = dbcontext.arquivoes.Find(id);
                files.DESCRICAO = descricao;
                dbcontext.SaveChanges();
            }
            catch (Exception error)
            {
                throw new Exception();
            }
        }


        //
        // GET: /Arquivos/Create
        [HttpPost]
        public void PostFile(arquivo arquivoContext)
        {
            HttpPostedFileBase file = Request.Files[0];

            if (file.ContentLength > 60000000)
            {
                //return RedirectToAction("ArquivoInfo", new { msg = "Arquivo maior que 50 mb" });
                throw new Exception();
            }
            else
            {
                try
                {
                    Random rnd = new Random();
                    int hash = rnd.Next(1, 99999999);

                    string filepath = string.Concat("/", ConfigurationManager.AppSettings["File.FolderName"], "/" + hash + "_", file.FileName);
                    file.SaveAs(Server.MapPath(filepath));

                    arquivoContext.PATHARQUIVO = filepath;
                    arquivoContext.ATIVO = true;
                    arquivoContext.NOMEARQUIVO = file.FileName;
                    arquivoContext.IDUSUARIO = UserBussiness.IdUser;
                    arquivoContext.DATAENVIOARQUIVO = DateTime.Now;
                    dbcontext.arquivoes.Add(arquivoContext);
                    dbcontext.SaveChanges();
                }
                catch (Exception error)
                {
                    throw new Exception();
                    error.Message.ToString();
                }
            }
        }
    }
}

ProjetoIntegrador/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using ProjetoIntegrador.Models;
using ProjetoIntegrador.Bussiness;
using System.Net;
using System.Configuration;
using System.IO;
using TestImageCrop;


namespace ProjetoIntegrador.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        projetointegradorContext dbcontext = new projetointegradorContext();

        //
        // GET: /Usuario/Index
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Usuario/Perfil
        public ActionResult Perfil()
        {
            var user = dbcontext.usuarios.Find(UserBussiness.IdUser);
            return View(user);
        }

        //
        // POST: /Usuario/Perfil
        [HttpPost]
        public ActionResult Perfil(usuario user)
        {
            try
            {
                var userContext = dbcontext.usuarios.Find(user.IDUSUARIO);

                userContext.NOMEUSUARIO = user.NOMEUSUARIO;
                userContext.SENHAUSUARIO = user.SENHAUSUARIO;
                userContext.EMAILUSUARIO = user.EMAILUSUARIO;
                //userContext.PATHIMAGEM = user.PATHIMAGEM;
                userContext.OBJETIVO = user.OBJETIVO;
                userContext.PERFIL = user.PERFIL;
                userContext.SOBREMIM = user.SOBREMIM;
                userContext.TELEFONEUSUARIO = user.TELEFONEUSUARIO;
                userContext.SEXOUSUARIO = user.SEXOUSUARIO;
                
                dbcontext.SaveChanges();

                return RedirectToAction("Perfil", new { msg="salvo" });
            }
            catch (Exception erro)
            {
                erro.Message.ToString();
            }
            return View(user);
        }
		
		//
        // POST: /Usuario/CropImage
		[HttpPost]
        public virtual ActionResult CropImage(
            string imagePath,
            int? cropPointX,
            int? cropPointY,
            int? imageCropWidth,
            int? imageCropHeight)
        {
            if (string.IsNullOrEmpty(imagePath)
                || !cropPointX.HasValue
                || !cropPointY.HasValue
                || !imageCropWidth.HasValue
                || !imageCropHeight.HasValue)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }

            byte[] imageBytes = System.IO.File.ReadAllBytes(Server.MapPath(imagePath));
            byte[] croppedImage = ImageHelper.CropImage(imageBytes, cropPointX.Value, cropPointY.Value, imageCropWidth.Value, imageCropHeight.Value);

            string tempFolderName = Server.MapPath("~/" + ConfigurationManager.AppSettings["Image.FolderName"]);
            string fileName = Path.GetFileName(imagePath);

            try
            {
                FileHelper.SaveFile(croppedImage, Path.Combine(tempFolderName, fileName));
            }
            catch (Exception ex)
            {
                //Log an error     
                return new HttpStatusCodeResult((int)HttpStatusCode.InternalServerError);
            }

            string photoPath = string.Concat("/", ConfigurationManager.AppSettings["Image.FolderName"], "/", fileName);
            return Json(new { photoPath = photoPath }, JsonRequestBehavior.AllowGet);
        }

        //
        // POST: /Usuario/UploadImage
        [HttpPost]
        public virtual ActionResult UploadImage(HttpPostedFileBase file)
        {
            HttpPostedFileBase postedFile = Request.Files[0];

            Random rnd = new Random();
            int idImg = rnd.Next(1, 99999999);

            //file.SaveAs(string.Concat("~/", ConfigurationManager.AppSettings["Image.FolderName"], "/", idImg, ".jpg"));

            string imbpath = string.Concat("/", ConfigurationManager.AppSettings["Image.FolderName"], "/", idImg, ".jpg");

            file.SaveAs(Server.MapPath(imbpath));

            var user = dbcontext.usuarios.Find(UserBussiness.IdUser);
            user.PATHIMAGEM = imbpath;
            dbcontext.SaveChanges();
            
            return Json(new { imbpath = imbpath }, JsonRequestBehavior.AllowGet);
        }

    }
}

ProjetoIntegrador/Views/Shared/_Footer.cshtml
<div id="footer" style="position: fixed; bottom: 0px; top: auto; z-index: 999999; margin-top: 200px !important;">
    <p>
        allShare - Compartilhando arquivos
			<span class="font-grey-4">|</span>
        © Copyright 2017
    </p>
    <a href="#" class="gototop">
        <i class="fa fa-arrow-up"></i>
    </a>
</div>
</body>
</html>

ProjetoIntegrador/Views/Shared/_Head.cshtml
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
		<!-- Apple devices fullscreen -->
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<!-- Apple devices fullscreen -->
		<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
		<title>allShare - Dashboard</title>
		<!-- Bootstrap -->
		<link rel="stylesheet" href="~/Scripts/css/bootstrap.min.css">
		<!-- jQuery UI -->
		<link rel="stylesheet" href="~/Scripts/css/plugins/jquery-ui.min.css">
		<!-- PageGuide -->
		<link rel="stylesheet" href="~/Scripts/css/plugins/pageguide.css">
		<!-- Fullcalendar -->
		<link rel="stylesheet" href="~/Scripts/css/plugins/fullcalendar.css">
		<link rel="stylesheet" href="~/Scripts/css/plugins/fullcalendar.print.css" media="print">
		<!-- chosen -->
		<link rel="stylesheet" href="~/Scripts/css/plugins/chosen.css">
		<!-- select2 -->
		<link rel="stylesheet" href="~/Scripts/css/plugins/select2.css">
		<!-- File Upload -->
		<link rel="stylesheet" href="~/Scripts/css/jquery.fileupload.css">
		
        <!-- File Crop Image -->
		<link rel="stylesheet" href="~/Scripts/css/cropper.min.css">

        <!-- Croppie -->
        <link href="~/Scripts/css/croppie.css" rel="stylesheet" />
		
		<!-- JCROP -->
		<link href="~/JsLibraries/Jcrop-v0.9.12/css/jquery.Jcrop.min.css" rel="stylesheet" />
		
        <!-- Alertfy -->
        <link href="~/Scripts/css/alertify.css" rel="stylesheet" />
        
        <!-- icheck -->
		<!--<link rel="stylesheet" href="~/Scripts/css/plugins/all.css">-->
		<!-- Theme CSS -->
		<link rel="stylesheet" href="~/Scripts/css/style.css">
		<!-- Color CSS -->
		<link rel="stylesheet" href="~/Scripts/css/themes.css">

        <!-- ColorBox -->
        <link href="~/Scripts/css/colorbox.css" rel="stylesheet" />
		<!-- jQuery -->
		<script src="~/Scripts/js/jquery.min.js"></script>
		<!-- Nice Scroll -->
		<script src="~/Scripts/js/plugins/jquery.nicescroll.min.js"></script>
		<!-- jQuery UI -->
		<script src="~/Scripts/js/plugins/jquery-ui.js"></script>
		<!-- Touch enable for jquery UI -->
		<script src="~/Scripts/js/plugins/jquery.touch-punch.min.js"></script>
		<!-- slimScroll -->
		<script src="~/Scripts/js/plugins/jquery.slimscroll.min.js"></script>
		<!-- Bootstrap -->
		<script src="~/Scripts/js/bootstrap.min.js"></script>
		<!-- vmap -->
		<script src="~/Scripts/js/plugins/vmap/jquery.vmap.min.js"></script>
		<script src="~/Scripts/js/plugins/vmap/jquery.vmap.world.js"></script>
		<script src="~/Scripts/js/plugins/vmap/jquery.vmap.sampledata.js"></script>
		<!-- Bootbox -->
		<script src="~/Scripts/js/plugins/jquery.bootbox.js"></script>
        <!-- ColorBox -->
        <script src="~/Scripts/js/jquery.colorbox.js"></script>
		<!-- Flot -->
		<script src="~/Scripts/js/plugins/flot/jquery.flot.min.js"></script>
		<script src="~/Scripts/js/plugins/flot/jquery.flot.bar.order.min.js"></script>
		<script src="~/Scripts/js/plugins/flot/jquery.flot.pie.min.js"></script>
		<script src="~/Scripts/js/plugins/flot/jquery.flot.resize.min.js"></script>
		<!-- imagesLoaded -->
		<script src="~/Scripts/js/plugins/jquery.imagesloaded.min.js"></script>
		<!-- PageGuide -->
		<script src="~/Scripts/js/plugins/jquery.pageguide.js"></script>
		<!-- FullCalendar -->
		<script src="~/Scripts/js/plugins/fullcalendar/moment.min.js"></script>
		<script src="~/Scripts/js/plugins/fullcalendar/fullcalendar.min.js"></script>
		<!-- Chosen -->
		<script src="~/Scripts/js/plugins/chosen.jquery.min.js"></script>
		<!-- select2 -->
		<script src="~/Scripts/js/plugins/select2.min.js"></script>
		<!-- icheck -->
		<script src="~/Scripts/js/plugins/jquery.icheck.min.js"></script>
		<!-- Theme framework -->
		<script src="~/Scripts/js/eakroko.min.js"></script>
		<!-- Upload file -->
		<script src="~/Scripts/js/jquery.fileupload.js"></script>
        <!-- Upload Crop Image -->
		<script src="~/Scripts/js/cropper.min.js"></script>
        <!-- Croppie -->
        <script src="~/Scripts/js/croppie.js"></script>
		<!-- Theme scripts -->
		<script src="~/Scripts/js/application.min.js"></script>
        <!-- Alertfy -->
		<script src="~/Scripts/js/alertify.js"></script>
		<!-- JCROP -->
		<script src="~/JsLibraries/Jcrop-v0.9.12/js/jquery.Jcrop.min.js"></script>
        <!-- JQueryMask -->
        <script src="~/Scripts/js/jquery.mask.min.js"></script>
        <!-- Main scripts -->
		<script src="~/Scripts/js/app.main.js"></script>
		<!-- Just for demonstration -->
		<script src="~/Scripts/js/demonstration.min.js"></script>
		<!--[if lte IE 9]>
		<script src="~/Scripts/js/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
		<![endif]-->
		<!-- Favicon -->
		<link rel="shortcut icon" href="~/Scripts/img/favicon.ico" />
		<!-- Apple devices Homescreen icon -->
		<link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png" />
	</head>
	<body>
        @if (HttpContext.Current.User.Identity.IsAuthenticated)
        {
            @Html.Partial("_Nav")   
        }else{
            @Html.Partial("_NavLogin")
        }

ProjetoIntegrador/Views/Shared/_Layout.cshtml
@Html.Partial("_Head")
<div class="container" id="content">
    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        @Html.Partial("_NavLeft")
    }
    <div id="main">
        <div class="container-fluid">
            <div class="m-t-20 page-header">
                <!--
			<div class="pull-left">
				<h1>Dashboard</h1>
			</div>
			<div class="breadcrumbs">
				<ul>
					<li>
						<a href="more-login.html">Home</a>
						<i class="fa fa-angle-right"></i>
					</li>
					<li>
						<a href="index.html">Dashboard</a>
					</li>
				</ul>
				<div class="close-bread">
					<a href="#">
						<i class="fa fa-times"></i>
					</a>
				</div>
			</div>
			-->
            </div>
            @RenderBody()
        </div>
    </div>
</div>
@Html.Partial("_Footer")

ProjetoIntegrador/Views/Shared/_Message.cshtml
@{
    try
    {
        var msg = Request.QueryString["msg"].ToString();
        switch (msg)
        {
            case "loginerro":
    <script>
        alertify.error("Login ou Senha inválido");
    </script>
                break;
            case "salvo":
    <script>
        alertify.success("Salvo com sucesso");
    </script>
                break;
            case "filerm":
    <script>
        alertify.success("Arquivo removido com sucesso!");
    </script>
                break;
            default:
                break;
        }
    }
    catch (Exception)
    {
    }
}

ProjetoIntegrador/Views/Shared/_Nav.cshtml
<div id="navigation" class="navbar-fixed-top">
	<div class="container-fluid">
		<a href="@Url.Action("Index", "Home")" id="brand">allShare</a>
		<a href="#" class="toggle-nav" rel="tooltip" data-placement="bottom" title="Esconder Menu">
		<i class="fa fa-bars"></i>
		</a>
		<ul class='main-nav'>
			<!--
			<li class='active'>
				<a href="index.html">
					<span>Dashboard</span>
				</a>
			</li>
			<li>
			-->
		</ul>
		<!-- #include file="user-drop.asp" -->
        @Html.Partial("_UserDropMenu")
	</div>
</div>

ProjetoIntegrador/Views/Shared/_NavLeft.cshtml
<div id="left" class="ui-sortable ui-resizable">
    <form action="@Url.Action("ListAmigos", "Amigos")" method="GET" class="search-form">
        <div class="search-pane">
            <input type="text" name="search" placeholder="Procure amigos...">
            <button type="submit">
                <i class="fa fa-search"></i>
            </button>
        </div>
    </form>
    <div class="subnav">
        <div class="subnav-title ui-sortable-handle">
            <a href="#" class="toggle-subnav">
                <i class="fa fa-angle-down"></i>
                <span>Menu</span>
            </a>
        </div>
        <ul class="subnav-menu">
            <li>
                <a href="@Url.Action("Index", "Amigos")">Amigos</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Arquivos")">Arquivos</a>
            </li>
        </ul>
    </div>
    <div class="ui-resizable-handle ui-resizable-e" style="z-index: 90; height: 346px;"></div>
</div>

ProjetoIntegrador/Views/Shared/_NavLogin.cshtml
@model ProjetoIntegrador.Models.Login
<div id="navigation" class="navbar-fixed-top">
    <div class="container-fluid">
        <a href="#" id="brand">allShare</a>
        <ul class='main-nav'>
            <!--
			<li class='active'>
				<a href="index.html">
					<span>Dashboard</span>
				</a>
			</li>
			<li>
			-->
        </ul>
        <div class="user-login">
            @using (Html.BeginForm("Login", "Home", FormMethod.Post))
            {
                <div class="col-sm-4">
                    @*<input type="text" name="login" id="login" placeholder="login" class="form-control">*@
                    @Html.TextBoxFor(model => model.UserLogin, new { @placeholder="Login", @class="form-control" })
                </div>
                <div class="col-sm-4">
                    @*<input type="text" name="pass" id="pass" placeholder="Senha" class="form-control">*@
                    @Html.PasswordFor(model => model.UserPass, new { @placeholder="Senha", @class="form-control" })
                </div>
                <div class="col-sm-4">
                    @*<a href="index.asp" class="btn">entrar</a>*@
                    <input type="submit" class="btn" value="Logar"/>
                </div> 
            }
        </div>
    </div>
</div>

ProjetoIntegrador/Views/Shared/_PagedList.cshtml
@using PagedList.Mvc;

<div class="highlight-toolbar">
    <div class="pull-left">
        <div class="btn-toolbar">
            <div class="btn-group text">
                Página
				<strong>@(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)</strong>
                de <strong>@Model.PageCount</strong>
            </div>
        </div>
    </div>
    <div class="pull-right">
        <div class="btn-toolbar">
            <div class="btn-group">
                @if (Model.HasNextPage)
                {
                    <a href="@Url.Action("Index", "Amigos", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })" class="btn">
                        <i class="fa fa-angle-right"></i>
                    </a>
                }
                @if (Model.HasPreviousPage)
                {        
                    <a href="@Url.Action("Index", "Amigos", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })" class="btn">
                        <i class="fa fa-angle-left"></i>
                    </a>
                }
            </div>
        </div>
    </div>
</div>

ProjetoIntegrador/Views/Shared/_UserDropMenu.cshtml
@using ProjetoIntegrador.Bussiness;
<div class="user">
	<div class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">@UserBussiness.NameUser
		<img src="@UserBussiness.ImageFromUser" alt="">
		</a>
		<ul class="dropdown-menu pull-right">
			<li>
				<a href="@Url.Action("Perfil", "Usuario")">Editar perfil</a>
			</li>
			@*<li>
				<a href="#">Configurações</a>
			</li>*@
			<li>
				<a href="@Url.Action("LogOut", "Home")">Sair</a>
			</li>
		</ul>
	</div>
</div>